name: Trigger Webhook on Check Suite Completion and PR Events

on:
  push:  # 监听所有分支的 push 事件
    branches:
      - '**'
  check_suite:
    types:
      - completed  # 监听检查完成的事件
  pull_request:
    types:
      - opened  # 监听 PR 发起的事件
      - reopened  # 监听 PR 重新打开的事件

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Debug Event Payload
      run: echo "${{ toJson(github.event) }}"

    - name: Send Webhook on PR Opened or Reopened
      if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened')
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "仓库 ${{ github.repository }} 有新的 PR：\n发起者: ${{ github.actor }}\nPR 标题: ${{ github.event.pull_request.title }}\nPR 链接: ${{ github.event.pull_request.html_url }}"
              }
            }' \
        https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}

    - name: Send Webhook on Check Suite Success for PR
      if: github.event.check_suite.conclusion == 'success' && github.event.check_suite.pull_requests != ''
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "仓库 ${{ github.repository }} 的 PR 检查已通过：\n检查者: ${{ github.actor }}\nPR 链接: ${{ github.event.check_suite.pull_requests[0].html_url }}\n检查详情: ${{ github.event.check_suite.url }}"
              }
            }' \
        https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}

    - name: Send Webhook on Check Suite Failure for PR
      if: github.event.check_suite.conclusion == 'failure' && github.event.check_suite.pull_requests != ''
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "仓库 ${{ github.repository }} 的 PR 检查失败：\n检查者: ${{ github.actor }}\nPR 链接: ${{ github.event.check_suite.pull_requests[0].html_url }}\n检查详情: ${{ github.event.check_suite.url }}"
              }
            }' \
        https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}