name: Trigger Webhook on Push, PR, and Check Runs

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Send Webhook on Push
      if: github.event_name == 'push'
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "仓库 ${{ github.repository }} 收到新的推送：\n推送者: ${{ github.actor }}\n提交信息: ${{ github.sha }}\n推送详情: ${{ github.event.head_commit.url }}"
              }
            }' \
        https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}

    - name: Send Webhook on PR
      if: github.event_name == 'pull_request'
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "仓库 ${{ github.repository }} 收到新的拉取请求：\n请求者: ${{ github.actor }}\nPR 标题: ${{ github.event.pull_request.title }}\nPR 链接: ${{ github.event.pull_request.html_url }}"
              }
            }' \
        https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}

    - name: Send Webhook on Check Run Success
      if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "仓库 ${{ github.repository }} 的工作流运行已成功完成：\n状态: ${{ github.event.workflow_run.conclusion }}\n详情: ${{ github.event.workflow_run.html_url }}"
              }
            }' \
        https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}

    - name: Send Webhook on Check Run Failure
      if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure'
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "仓库 ${{ github.repository }} 的工作流运行失败：\n状态: ${{ github.event.workflow_run.conclusion }}\n详情: ${{ github.event.workflow_run.html_url }}"
              }
            }' \
        https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}