name: Trigger Webhook on Push, PR, and PR Merge

on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - synchronize
      - closed
      - ready_for_review

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Send Webhook on Push
      if: github.event_name == 'push'
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "仓库 ${{ github.repository }} 收到新的推送：\n推送者: ${{ github.actor }}\n提交信息: ${{ github.sha }}\n推送详情: ${{ github.event.head_commit.url }}"
              }
            }' \
        https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}

    - name: Send Webhook on PR
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "仓库 ${{ github.repository }} 收到新的拉取请求：\n请求者: ${{ github.actor }}\nPR 标题: ${{ github.event.pull_request.title }}\nPR 链接: ${{ github.event.pull_request.html_url }}"
              }
            }' \
        https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}

    - name: Send Webhook on PR Merge
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "仓库 ${{ github.repository }} 的拉取请求已合并：\n请求者: ${{ github.actor }}\nPR 标题: ${{ github.event.pull_request.title }}\nPR 链接: ${{ github.event.pull_request.html_url }}"
              }
            }' \
        https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}

    - name: Send Webhook on PR Ready for Merge
      if: github.event_name == 'pull_request' && (github.event.action == 'synchronize' || github.event.action == 'ready_for_review')
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "仓库 ${{ github.repository }} 的拉取请求已更新，可以合并：\n请求者: ${{ github.actor }}\nPR 标题: ${{ github.event.pull_request.title }}\nPR 链接: ${{ github.event.pull_request.html_url }}"
              }
            }' \
        https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}